# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetrics.proto\"\x89\x01\n\x0eMetricsRequest\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x11\n\tcpu_usage\x18\x02 \x01(\x02\x12\x14\n\x0cmemory_usage\x18\x03 \x01(\x02\x12\x12\n\ndisk_usage\x18\x04 \x01(\x02\x12\x12\n\nnetwork_in\x18\x05 \x01(\x02\x12\x13\n\x0bnetwork_out\x18\x06 \x01(\x02\"3\n\x0fMetricsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2D\n\x0eMetricsService\x12\x32\n\rReportMetrics\x12\x0f.MetricsRequest\x1a\x10.MetricsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICSREQUEST']._serialized_start=18
  _globals['_METRICSREQUEST']._serialized_end=155
  _globals['_METRICSRESPONSE']._serialized_start=157
  _globals['_METRICSRESPONSE']._serialized_end=208
  _globals['_METRICSSERVICE']._serialized_start=210
  _globals['_METRICSSERVICE']._serialized_end=278
# @@protoc_insertion_point(module_scope)
